[features]
seeds = false
skip-lint = false

[programs.localnet]
referral = "RefEr4lP3yXyZ9qK3mN8vW2jR5tY7uI6oP1aS4dF0gH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
